LOG:  database system was shut down at 2016-08-04 18:05:36 EDT
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received fast shutdown request
LOG:  aborting any active transactions
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-08-04 18:07:34 EDT
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
FATAL:  lock file "postmaster.pid" already exists
HINT:  Is another postmaster (PID 38641) running in data directory "/usr/local/var/postgres9.5"?
LOG:  received fast shutdown request
LOG:  aborting any active transactions
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-08-04 18:14:39 EDT
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  could not open file "postmaster.pid": No such file or directory
LOG:  performing immediate shutdown because data directory lock file is invalid
LOG:  received immediate shutdown request
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
LOG:  could not open temporary statistics file "pg_stat/global.tmp": No such file or directory
LOG:  database system was shut down at 2016-08-10 12:53:10 EDT
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  database system was shut down at 2016-08-17 21:19:47 EDT
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
ERROR:  relation "inv_app_item" already exists
STATEMENT:  ALTER TABLE "inv_app_photo" RENAME TO "inv_app_item"
ERROR:  relation "inv_app_item" already exists
STATEMENT:  ALTER TABLE "inv_app_photo" RENAME TO "inv_app_item"
ERROR:  relation "inv_app_item" already exists
STATEMENT:  ALTER TABLE "inv_app_photo" RENAME TO "inv_app_item"
LOG:  using stale statistics instead of current ones because stats collector is not responding
LOG:  using stale statistics instead of current ones because stats collector is not responding
ERROR:  column inv_app_photo.image does not exist at character 30
STATEMENT:  SELECT "inv_app_photo"."id", "inv_app_photo"."image" FROM "inv_app_photo" ORDER BY "inv_app_photo"."id" DESC
ERROR:  column inv_app_photo.image does not exist at character 30
STATEMENT:  SELECT "inv_app_photo"."id", "inv_app_photo"."image" FROM "inv_app_photo" ORDER BY "inv_app_photo"."id" DESC LIMIT 21
ERROR:  column inv_app_photo.image does not exist at character 30
STATEMENT:  SELECT "inv_app_photo"."id", "inv_app_photo"."image" FROM "inv_app_photo" ORDER BY "inv_app_photo"."id" DESC LIMIT 21
ERROR:  column inv_app_photo.image does not exist at character 30
STATEMENT:  SELECT "inv_app_photo"."id", "inv_app_photo"."image" FROM "inv_app_photo" ORDER BY "inv_app_photo"."id" DESC LIMIT 21
ERROR:  column inv_app_photo.image does not exist at character 30
STATEMENT:  SELECT "inv_app_photo"."id", "inv_app_photo"."image" FROM "inv_app_photo" ORDER BY "inv_app_photo"."id" DESC
ERROR:  column inv_app_photo.image does not exist at character 30
STATEMENT:  SELECT "inv_app_photo"."id", "inv_app_photo"."image" FROM "inv_app_photo" ORDER BY "inv_app_photo"."id" DESC LIMIT 21
ERROR:  column inv_app_photo.image does not exist at character 30
STATEMENT:  SELECT "inv_app_photo"."id", "inv_app_photo"."image" FROM "inv_app_photo" ORDER BY "inv_app_photo"."id" DESC LIMIT 21
ERROR:  column inv_app_photo.image does not exist at character 30
STATEMENT:  SELECT "inv_app_photo"."id", "inv_app_photo"."image" FROM "inv_app_photo" ORDER BY "inv_app_photo"."id" DESC LIMIT 21
ERROR:  column inv_app_album.title does not exist at character 30
STATEMENT:  SELECT "inv_app_album"."id", "inv_app_album"."title", "inv_app_album"."highlight_id" FROM "inv_app_album" ORDER BY "inv_app_album"."id" DESC
ERROR:  column inv_app_album.title does not exist at character 30
STATEMENT:  SELECT "inv_app_album"."id", "inv_app_album"."title", "inv_app_album"."highlight_id" FROM "inv_app_album" ORDER BY "inv_app_album"."id" DESC LIMIT 21
ERROR:  column inv_app_album.title does not exist at character 30
STATEMENT:  SELECT "inv_app_album"."id", "inv_app_album"."title", "inv_app_album"."highlight_id" FROM "inv_app_album" ORDER BY "inv_app_album"."id" DESC LIMIT 21
ERROR:  column inv_app_album.title does not exist at character 30
STATEMENT:  SELECT "inv_app_album"."id", "inv_app_album"."title", "inv_app_album"."highlight_id" FROM "inv_app_album" ORDER BY "inv_app_album"."id" DESC LIMIT 21
ERROR:  relation "inv_app_image" does not exist at character 116
STATEMENT:  SELECT "inv_app_image"."id", "inv_app_image"."title", "inv_app_image"."data", "inv_app_image"."date_uploaded" FROM "inv_app_image"
ERROR:  relation "inv_app_image" does not exist at character 116
STATEMENT:  SELECT "inv_app_image"."id", "inv_app_image"."title", "inv_app_image"."data", "inv_app_image"."date_uploaded" FROM "inv_app_image" LIMIT 21
ERROR:  relation "inv_app_tag" does not exist at character 35
STATEMENT:  SELECT COUNT(*) AS "__count" FROM "inv_app_tag"
ERROR:  relation "inv_app_tag" does not exist at character 54
STATEMENT:  SELECT "inv_app_tag"."id", "inv_app_tag"."name" FROM "inv_app_tag" ORDER BY "inv_app_tag"."id" DESC LIMIT 21
ERROR:  relation "inv_app_image" does not exist at character 35
STATEMENT:  SELECT COUNT(*) AS "__count" FROM "inv_app_image"
ERROR:  relation "inv_app_image" does not exist at character 116
STATEMENT:  SELECT "inv_app_image"."id", "inv_app_image"."title", "inv_app_image"."data", "inv_app_image"."date_uploaded" FROM "inv_app_image" ORDER BY "inv_app_image"."id" DESC LIMIT 21
ERROR:  relation "inv_app_image" does not exist at character 35
STATEMENT:  SELECT COUNT(*) AS "__count" FROM "inv_app_image"
ERROR:  relation "inv_app_image" does not exist at character 116
STATEMENT:  SELECT "inv_app_image"."id", "inv_app_image"."title", "inv_app_image"."data", "inv_app_image"."date_uploaded" FROM "inv_app_image" ORDER BY "inv_app_image"."id" DESC LIMIT 21
ERROR:  relation "inv_app_album" already exists
STATEMENT:  CREATE TABLE "inv_app_album" ("id" serial NOT NULL PRIMARY KEY, "title" varchar(250) NOT NULL)
ERROR:  relation "inv_app_album" already exists
STATEMENT:  CREATE TABLE "inv_app_album" ("id" serial NOT NULL PRIMARY KEY, "title" varchar(250) NOT NULL)
ERROR:  relation "inv_app_image" does not exist at character 35
STATEMENT:  SELECT COUNT(*) AS "__count" FROM "inv_app_image"
ERROR:  relation "inv_app_image" does not exist at character 116
STATEMENT:  SELECT "inv_app_image"."id", "inv_app_image"."title", "inv_app_image"."data", "inv_app_image"."date_uploaded" FROM "inv_app_image" ORDER BY "inv_app_image"."id" DESC LIMIT 21
ERROR:  column "highlight_id" of relation "inv_app_album" does not exist
STATEMENT:  ALTER TABLE "inv_app_album" DROP COLUMN "highlight_id" CASCADE
ERROR:  column inv_app_product.image does not exist at character 32
STATEMENT:  SELECT "inv_app_product"."id", "inv_app_product"."image" FROM "inv_app_product" LIMIT 1
ERROR:  column inv_app_product.image does not exist at character 32
STATEMENT:  SELECT "inv_app_product"."id", "inv_app_product"."image" FROM "inv_app_product" LIMIT 1
ERROR:  column inv_app_product.image does not exist at character 32
STATEMENT:  SELECT "inv_app_product"."id", "inv_app_product"."image" FROM "inv_app_product" LIMIT 1
ERROR:  column inv_app_product.image does not exist at character 32
STATEMENT:  SELECT "inv_app_product"."id", "inv_app_product"."image" FROM "inv_app_product" LIMIT 1
ERROR:  column inv_app_product.image does not exist at character 32
STATEMENT:  SELECT "inv_app_product"."id", "inv_app_product"."image" FROM "inv_app_product" LIMIT 1
ERROR:  column inv_app_product.image does not exist at character 32
STATEMENT:  SELECT "inv_app_product"."id", "inv_app_product"."image" FROM "inv_app_product" LIMIT 1
ERROR:  column inv_app_product.image does not exist at character 32
STATEMENT:  SELECT "inv_app_product"."id", "inv_app_product"."image" FROM "inv_app_product" LIMIT 1
ERROR:  column inv_app_product.image does not exist at character 32
STATEMENT:  SELECT "inv_app_product"."id", "inv_app_product"."image" FROM "inv_app_product" LIMIT 1
ERROR:  column inv_app_product.image does not exist at character 32
STATEMENT:  SELECT "inv_app_product"."id", "inv_app_product"."image" FROM "inv_app_product" LIMIT 1
ERROR:  column inv_app_product.image does not exist at character 32
STATEMENT:  SELECT "inv_app_product"."id", "inv_app_product"."image" FROM "inv_app_product" ORDER BY "inv_app_product"."id" DESC
ERROR:  column inv_app_product.image does not exist at character 32
STATEMENT:  SELECT "inv_app_product"."id", "inv_app_product"."image" FROM "inv_app_product" ORDER BY "inv_app_product"."id" DESC LIMIT 21
ERROR:  column inv_app_product.image does not exist at character 32
STATEMENT:  SELECT "inv_app_product"."id", "inv_app_product"."image" FROM "inv_app_product" ORDER BY "inv_app_product"."id" DESC LIMIT 21
ERROR:  column inv_app_product.image does not exist at character 32
STATEMENT:  SELECT "inv_app_product"."id", "inv_app_product"."image" FROM "inv_app_product" ORDER BY "inv_app_product"."id" DESC LIMIT 21
ERROR:  cannot truncate a table referenced in a foreign key constraint
DETAIL:  Table "filer_file" references "django_content_type".
HINT:  Truncate table "filer_file" at the same time, or use TRUNCATE ... CASCADE.
STATEMENT:  TRUNCATE "django_content_type", "auth_permission", "django_session", "auth_user_user_permissions", "auth_user_groups", "auth_group", "inv_app_inv_user", "inv_app_product", "django_admin_log", "auth_user", "django_site", "auth_group_permissions";
ERROR:  syntax error at or near "exit" at character 1
STATEMENT:  exit()
	exit
	quit
	;
ERROR:  syntax error at or near "quit" at character 1
STATEMENT:  quit;
ERROR:  syntax error at or near "quit" at character 1
STATEMENT:  quit()
	;
ERROR:  syntax error at or near "q" at character 1
STATEMENT:  q
	;
FATAL:  database "inventory" does not exist
FATAL:  database "inventory" does not exist
FATAL:  database "inventory" does not exist
ERROR:  syntax error at or near "createdb" at character 1
STATEMENT:  createdb
	inventory;
ERROR:  syntax error at or near "inventory" at character 8
STATEMENT:  create inventory;
ERROR:  relation "inv_app_product" already exists
STATEMENT:  CREATE TABLE "inv_app_product" ("id" serial NOT NULL PRIMARY KEY, "photo" varchar(100) NOT NULL)
ERROR:  relation "inv_app_product" already exists
STATEMENT:  CREATE TABLE "inv_app_product" ("id" serial NOT NULL PRIMARY KEY, "photo" varchar(100) NOT NULL)
ERROR:  relation "inv_app_product" already exists
STATEMENT:  CREATE TABLE "inv_app_product" ("id" serial NOT NULL PRIMARY KEY, "photo" varchar(100) NOT NULL)
ERROR:  relation "inv_app_product" already exists
STATEMENT:  CREATE TABLE "inv_app_product" ("id" serial NOT NULL PRIMARY KEY, "photo" varchar(100) NOT NULL)
ERROR:  syntax error at or near "/" at character 1
STATEMENT:  /c postgres
	drop database inventory
	;
